#!/usr/bin/env node

'use strict'

const http = require('http')
const { spawn } = require('child_process')
const serve = require('serve-static')

if (process.env.NODE_ENV === 'production') {
  require('../server')
} else {
  spawn('watchify', [
    '-v',
    '-o', 'apps/client/dist/bundle.js',
    'apps/client/main.js'
  ], { stdio: 'inherit' })
  const staticServer = serve('apps/client/dist')
  http.createServer((req, res) => {
    staticServer(req, res, next)

    function next (err) {
      if (err) {
        console.log(err.stack)
        res.statusCode = 500
        res.end('Internal server error')
        return
      }
      res.statusCode = 404
      res.end('File not found :-(')
    }
  })
  .listen(8080, () => {
    console.log('static server listening on port 8080')
  })
  spawn('nodemon', [
    '-w', 'server.js',
    '-w', 'index.js',
    '-w', 'services',
    '--',
    '-r', 'dotenv/config', 'server.js'
  ], { stdio: 'inherit' })
}
