#!/usr/bin/env node

'use strict'

const { spawn } = require('child_process')

if (process.env.NODE_ENV === 'production') {
  require('../server')
} else {
  spawn('watchify', [
    '-v',
    '-o', 'apps/client/dist/bundle.js',
    'apps/client/main.js'
  ], { stdio: 'inherit' })
  spawn('ecstatic', [
    'apps/client/dist',
    '--port', '8080'
  ], { stdio: 'inherit' })
  spawn('nodemon', [
    '-w', 'server.js',
    '-w', 'index.js',
    '-w', 'services',
    '--',
    '-r', 'dotenv/config', 'server.js'
  ], { stdio: 'inherit' })
}
